project_id = "ieinjhonepkudxxpmuly"

[functions.paypal-subscription]
verify_jwt = false

[functions.paypal-webhook]
verify_jwt = false

[functions.paypal-subscription-status]
verify_jwt = false

[functions.paypal-capture-consult]
verify_jwt = false
